services:
  # https://prometheus.io/docs/prometheus/latest/installation/#using-docker
  prometheus:
    image: "prom/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=10GB"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.page-title=Dogecoin Metrics Prometheus DB"
    # Uncomment to publish ports to the host machine
    #ports:
    #  - "9090"
    volumes:
      - "prom-data:/prometheus"
      - "./prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml"

  # https://grafana.com/docs/grafana/latest/installation/docker/
  # https://grafana.com/docs/grafana/latest/administration/configure-docker/
  grafana:
    image: "grafana/grafana"
    ports:
      - "0.0.0.0:80:3000"
    volumes:
      # Main data volume
      - "grafana-data:/var/lib/grafana"
      # Configuration that goes in /etc/grafana
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./grafana/dogecoin.json:/etc/grafana/provisioning/dashboards/dogecoin.json"

volumes:
  prom-data:
  grafana-data:
