{
 "title": "Dogecoin Nodes",
 "description": "Monitor your Dogecoin core node and aspects of the network.",
 "tags": [ "dogecoin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Blocks",
   "type": "stat",
   "description": "Number of Dogecoin blocks based on synced headers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(dogecoin_headers)" }
   ]
  },
  {
   "title": "Total peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dogecoin_peers)" }
   ]
  },
  {
   "title": "Block height by node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dogecoin_blocks", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "Number of peers that have been banned and the reason for the ban.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(dogecoin_banned_until) by (reason)",
     "legendFormat": "ban - {{ reason }}"
    },
    { "expr": "dogecoin_peers", "legendFormat": "{{hostname}}" }
   ]
  },
  {
   "title": "Blocks behind",
   "type": "graph",
   "description": "Headers synced minus block height",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dogecoin_headers - dogecoin_blocks",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Sent and received traffic rates",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(dogecoin_total_bytes_sent[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(irate(dogecoin_total_bytes_recv[10m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Daily Block Creation Rate",
   "type": "graph",
   "description": "Number of blocks created per day using different trailing rates.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(rate(dogecoin_blocks[3h])) * 3600 * 24)",
     "legendFormat": "3h"
    },
    {
     "expr": "floor(sum(rate(dogecoin_blocks[6h])) * 3600 * 24)",
     "legendFormat": "6h"
    },
    {
     "expr": "floor(sum(rate(dogecoin_blocks[12h])) * 3600 * 24)",
     "legendFormat": "12h"
    },
    {
     "expr": "floor(sum(rate(dogecoin_blocks[7d])) * 3600 * 24)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "description": "Difficulty value",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(dogecoin_difficulty)", "legendFormat": "difficulty" }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "graph",
   "description": "Estimated network hashes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(dogecoin_hashps)", "legendFormat": "120-blocks" },
    { "expr": "avg(dogecoin_hashps_neg1)", "legendFormat": "last-difficulty" }
   ]
  },
  {
   "title": "Chain Branches",
   "type": "graph",
   "description": "Number of tips seen in the chain.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "dogecoin_num_chaintips", "legendFormat": "{{hostname}}" }
   ]
  }
 ]
}